export const DATA_SOURCE = 'DATA_SOURCE';
export const OPENID_CLIENT = 'OPENID_CLIENT';

//

export const REPOSITORY_APELIDO = 'REPOSITORY_APELIDO';
export const REPOSITORY_PERIODO_LETIVO = 'REPOSITORY_PERIODO_LETIVO';
export const REPOSITORY_AULA_PROFESSOR = 'REPOSITORY_AULA_PROFESSOR';
export const REPOSITORY_PROFESSOR = 'REPOSITORY_PROFESSOR';
export const REPOSITORY_AULA = 'REPOSITORY_AULA';
export const REPOSITORY_SEMANA = 'REPOSITORY_SEMANA';
export const REPOSITORY_AULA_TURMA = 'REPOSITORY_AULA_TURMA';
export const REPOSITORY_TURMA = 'REPOSITORY_TURMA';
export const REPOSITORY_ETAPA = 'REPOSITORY_ETAPA';
export const REPOSITORY_UNIDADE_ESTUDANTIL = 'REPOSITORY_UNIDADE_ESTUDANTIL';
export const REPOSITORY_EVENTO = 'REPOSITORY_EVENTO';
export const REPOSITORY_UNIDADE_ESTUDANTIL_USUARIO =
  'REPOSITORY_UNIDADE_ESTUDANTIL_USUARIO';
export const REPOSITORY_GRUPO = 'REPOSITORY_GRUPO';
export const REPOSITORY_USUARIO = 'REPOSITORY_USUARIO';
export const REPOSITORY_MATERIA = 'REPOSITORY_MATERIA';

//

export const IS_PUBLIC_KEY = 'isPublic';

//

export const IS_PRODUCTION_MODE = process.env.NODE_ENV === 'production';
