import { PAINEL_PAGE_INSTITUICOES_BREADCRUMB_ITEMS } from '../PainelPageInstituicoes/PAINEL_PAGE_INSTITUICOES_BREADCRUMB_ITEMS';

export const PAINEL_PAGE_INSTITUICAO_BREADCRUMB_ITEMS = [
  ...PAINEL_PAGE_INSTITUICOES_BREADCRUMB_ITEMS,

  {
    label: 'Instituição',
  },
];
