services:
  server-db:
    image: postgres:15-alpine
    container_name: server-db
    volumes:
      - './volumes/postgres:/var/lib/postgresql/data'
    env_file:
      - .env
    ports:
      - 5432:5432
    